os: linux
dist: trusty
addons:
  chrome: stable

language: node_js

node_js:
  - 'node'

services:
  - docker
  - xvfb

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
  - npm install

# Init GUI
before_script:
  - "export DISPLAY=:99.0"
  #- apt-get install graphicsmagick # for e2e screenshots

script:
  - npm run lint
  - npm run test:single-run
  - npm run build:libs

cache:
  directories:
    - ./node_modules

deploy:
  github_token: $GITHUB_TOKEN
  provider: script
  script: "npm run deploy"
  skip_cleanup: true
  on:
    branch: master



notifications:
  email: false
